### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by xxr3376** [utek/pyseaweed#5]
I use this script to put billions of small images to seaweed, I got ``Cannot assign requested address`` error.

I've tried use `sysctl -w net.ipv4.tcp_timestamps=1` and `sysctl -w net.ipv4.tcp_tw_recycle=1` to cover this error, but after that the performance is so unstable: the speed will be 0 for minutes after a while of high performance (I believe it is waiting for old connection to close).

Because you don't use requests.session to keep the connection alive, requests will open a new connection every time I call post_file.

I did a ad-hoc fix: in `utils.py` : create a session by `session = requests.session()`, and replace all method likes `requests.*` by `session.*` , then I got a high and stable performance.

Please consider to use session for each WeedFS object for better performance.

**Comment by utek** [comment]
I'll take a look at it when I'll have a bit of time

**Comment by utek** [comment]
@xxr3376 Hi. I've pushed changes to master that should allow you to use session.

Just create object with `weed = WeedFS(use_session=True)`

Please let me know if that's working properly for you

**Comment by xxr3376** [comment]
That commit meets my fix, awesome.

I use seaweed as a global SSD cache for python program,  any performance improvement will make my program faster significantly. In fact, I wrote a very tiny client to get higher performance.

This is my client code [Nori](https://github.com/xxr3376/Nori) . It uses httplib2 for faster HTTP performance, cache volume address for less HTTP request, thread.local to avoid lock when using threading. According to my benchmark, this client achieves 3x speed than origin one ( only use request.session ) when fetching data with 30 threads. ( benchmark with 40-thread CPU and InfiniteBand)

**Comment by utek** [comment]
@xxr3376  [Nori](https://github.com/xxr3376/Nori) looks nice. I'll do some tests and maybe add/replace connection type to pyseaweed. Thanks
